CREATE DATABASE mytest;

CREATE TABLE word_count(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(255) NOT NULL ,
  count INT NOT NULL ,
  DT VARCHAR(23) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;